version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "7545:7545"   # Ethereum RPC
      - "8545:8545"   # Optional: for other services
    command: ganache-cli -a 10 -e 1000 -i 1337 --mnemonic "radio clown reduce human person fatigue excess they mosquito place multiply clap" --defaultBalanceEther 1000 --gasPrice 2000000000 --gasLimit 30000000
    networks:
      - blockchain-network
    restart: always

  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPPLYCHAIN_ADDRESS=0xYourDeployedContractAddressHere
      - NEXT_PUBLIC_ETHEREUM_NETWORK=1337
    depends_on:
      - ganache
    networks:
      - blockchain-network
    restart: always

networks:
  blockchain-network:
    driver: bridge

